name: CI
env:
  APP_NAME: lokidb
on:
  push:
    tags:
      - '**'
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
          cache: yarn
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@pixlabs'
      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: npm-cache-ubuntu-latest-publish
      - name: Install dependencies
        run: yarn install --ignore-scripts --frozen-lockfile --registry https://registry.npmjs.org --network-timeout 300000
      - name: Build
        run: yarn build --dist
      - name: Publish loki
        run: yarn publish dist/packages-dist/loki
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish fts
        run: yarn publish dist/packages-dist/full-text-search
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
